-- Employee Payroll Management System - Oracle schema

CREATE TABLE departments (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    department_name VARCHAR2(80) NOT NULL UNIQUE,
    location VARCHAR2(80)
);

CREATE TABLE employees (
    employee_id NUMBER PRIMARY KEY,
    first_name VARCHAR2(50) NOT NULL,
    last_name VARCHAR2(50) NOT NULL,
    email VARCHAR2(120) NOT NULL UNIQUE,
    phone VARCHAR2(20),
    hire_date DATE DEFAULT SYSDATE NOT NULL,
    job_title VARCHAR2(80) NOT NULL,
    department_id NUMBER NOT NULL,
    employment_status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
    CONSTRAINT fk_employee_department FOREIGN KEY (department_id)
        REFERENCES departments(department_id),
    CONSTRAINT ck_employment_status CHECK (employment_status IN ('ACTIVE','ON_LEAVE','INACTIVE'))
);

CREATE TABLE salary_structure (
    employee_id NUMBER PRIMARY KEY,
    basic_salary NUMBER(12,2) NOT NULL,
    hra NUMBER(12,2) DEFAULT 0 NOT NULL,
    allowances NUMBER(12,2) DEFAULT 0 NOT NULL,
    provident_fund NUMBER(12,2) DEFAULT 0 NOT NULL,
    tax_rate NUMBER(5,2) DEFAULT 0 NOT NULL,
    CONSTRAINT fk_salary_employee FOREIGN KEY (employee_id) REFERENCES employees(employee_id),
    CONSTRAINT ck_basic_salary CHECK (basic_salary > 0),
    CONSTRAINT ck_salary_components CHECK (hra >= 0 AND allowances >= 0 AND provident_fund >= 0),
    CONSTRAINT ck_tax_rate CHECK (tax_rate BETWEEN 0 AND 100)
);

CREATE TABLE attendance (
    attendance_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER NOT NULL,
    attendance_date DATE NOT NULL,
    status VARCHAR2(20) NOT NULL,
    CONSTRAINT fk_attendance_employee FOREIGN KEY (employee_id) REFERENCES employees(employee_id),
    CONSTRAINT uq_employee_attendance UNIQUE (employee_id, attendance_date),
    CONSTRAINT ck_attendance_status CHECK (status IN ('PRESENT','ABSENT','LEAVE','HOLIDAY'))
);

CREATE TABLE payroll (
    payroll_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id NUMBER NOT NULL,
    pay_month DATE NOT NULL,
    basic_salary NUMBER(12,2) NOT NULL,
    hra NUMBER(12,2) DEFAULT 0 NOT NULL,
    allowances NUMBER(12,2) DEFAULT 0 NOT NULL,
    bonus NUMBER(12,2) DEFAULT 0 NOT NULL,
    tax NUMBER(12,2) DEFAULT 0 NOT NULL,
    provident_fund NUMBER(12,2) DEFAULT 0 NOT NULL,
    other_deductions NUMBER(12,2) DEFAULT 0 NOT NULL,
    gross_salary NUMBER(12,2) NOT NULL,
    net_salary NUMBER(12,2) NOT NULL,
    processed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT fk_payroll_employee FOREIGN KEY (employee_id) REFERENCES employees(employee_id),
    CONSTRAINT uq_employee_pay_month UNIQUE (employee_id, pay_month),
    CONSTRAINT ck_payroll_nonnegative CHECK (
        basic_salary >= 0 AND hra >= 0 AND allowances >= 0 AND bonus >= 0 AND
        tax >= 0 AND provident_fund >= 0 AND other_deductions >= 0 AND
        gross_salary >= 0 AND net_salary >= 0
    )
);

CREATE TABLE payroll_audit (
    audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payroll_id NUMBER NOT NULL,
    employee_id NUMBER NOT NULL,
    old_net_salary NUMBER(12,2),
    new_net_salary NUMBER(12,2),
    action_type VARCHAR2(10) NOT NULL,
    changed_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    changed_by VARCHAR2(128) DEFAULT USER NOT NULL
);

CREATE INDEX idx_employees_department ON employees(department_id);
CREATE INDEX idx_attendance_employee_date ON attendance(employee_id, attendance_date);
CREATE INDEX idx_payroll_month ON payroll(pay_month);
